#ifndef CONSTANTES_H_INCLUDED
#define CONSTANTES_H_INCLUDED

#define LARGEUR_FENETRE  1500
#define HAUTEUR_FENETRE  900

#define HAUTEUR_SOL  200

#define LARGEUR_POTEAUX 10
#define HAUTEUR_POTEAUX 400

#define ABSCISSE_POTEAU1 245
#define ABSCISSE_POTEAU2 795
#define ABSCISSE_POTEAU3 1340
#define ORDONEE_POTEAUX 300

#define HAUTEUR_DISQUE 20
#define LARGEUR_PLUS_GRAND_DISQUE 300
#define TAILLE_T HAUTEUR_POTEAUX/HAUTEUR_DISQUE
#define VITESSE_PARCOURS_DISC 4
#define SOMMET_MAX_DES_DISQUES 260 

#endif // CONSTANTES_H_INCLUDED
